name: Terraform Apply

on:
    push:
        branches: ["main"]

permissions: 
    contents: read

jobs:
    terraform_apply:
        name: 'Terraform Apply'
        runs-on: ubuntu-latest

        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.5.6

            - name: Terraform Init
              run: terraform init

            - name: Terraform Format
              run: terraform fmt

            - name: Terraform Apply
              run: terraform apply
